from .agent_student import StudentAgent
from .memory import Memory

from .tools.tools_raspa import CoreMofLoader, ExecuteRaspa, InputFile, OutputParser, \
    FrameworkLoader, MoleculeLoader, SystemAgent
from .tools.tools import Tool

from mllm import Chat
from typing import Dict, List, Any
from .utils import *
import re


class RaspaAgent(StudentAgent):
    memory: Memory
    tools: Dict[str, Tool]
    system_prompt: str
    chat: Chat
    id: int

    molecule_memory: Memory
    framework_memory: Memory
    path: str
    path_add: str
    auto_run: bool

    def __init__(self, path="output", version="v1", provider="anthropic", csd_path=None, verbose=True,
                 active_learning=True):
        if csd_path is not None:
            framework_loader = FrameworkLoader(path, coremof=False, csd_path=csd_path)
        else:
            print("A CSD path is required to access the coremof files.")
            framework_loader = FrameworkLoader(path, coremof=False)

        raspa_tools = [
            # CoreMofLoader(path),
            framework_loader,
            # TrappeLoader(path),
            MoleculeLoader(path),
            ExecuteRaspa(agent=self),
            InputFile(),
            SystemAgent(path),
            # ReadFile(),
            # WriteFile(),
            # InspectFiles(),
            OutputParser()
        ]
        tools = {
            tool.name: tool
            for tool in raspa_tools
        }

        super().__init__(tools=tools, version=version, provider=provider, verbose=verbose)

        self.reset(path)  # base path
        self.path_add = ""  # add onto path for simulations
        self.auto_run = False
        self.current_todo_list = ""  # for todo list tracking
        self.add_raspa_prompt()
        self._advance_to_next_folder()
        self.reset(path)
        self.active_learning = active_learning

    def add_raspa_prompt(self):
        prompt = self._build_prompt("raspa", "v1")
        self.reset_system_prompt(prompt, append=True)

    def setup_path(self, path: str) -> None:
        os.makedirs(path, exist_ok=True)
        self.path = path
        for tool in self.tools.values():
            if hasattr(tool, "path"):
                tool.path = path
        return

    def set_path_add(self, path_add):
        self.path_add = path_add
        full_path = self.get_full_path()
        os.makedirs(full_path, exist_ok=True)
        for tool in self.tools.values():
            if hasattr(tool, "path_add"):
                tool.path_add = path_add
        return full_path

    def get_full_path(self):
        return os.path.join(self.path, self.path_add)

    def reset(self, path=None):
        if path is not None:
            self.setup_path(path)
        for tool in self.tools:
            if hasattr(tool, "has_file"):
                tool.has_file = False
        return

    def check_files(self):
        if all([tool.has_file for tool in self.tools if hasattr(tool, "has_file")]):
            return True
        return False

    def _check_ignore(self, file_name):
        # Return True is file should be ignored
        blacklist = ["Movies/", "VTK/", "Restart/", "run.sh"]
        for p in blacklist:
            if p in file_name:
                return True
        return False

    def _file_overview(self):
        current_directory = self.path_add
        files_all = [i for i in all_files(self.path) if self._check_ignore(i) is False]
        file_list = ", ".join(f"{f}" for f in files_all) if files_all else "Empty"
        # file_overview = f"\n\n<file_overview>\nCurrent directory: {current_directory}\nFiles:\n{file_list}\n</file_overview>"
        return file_list, current_directory

    def add_file_message(self):
        file_list, current_directory = self._file_overview()
        message = {
            "role": "assistant",
            'content':
                {
                    'type': 'text',
                    'text': json.dumps({
                        "info": "This is an automatic message by the system with the current file system. This is not generated by the user!",
                        "current_directory": current_directory,
                        "file_list": file_list,
                    })
                }
        }

        self.chat.messages.append(message)
        return self.chat_length() - 1

    def remove_file_message(self, file_message_index):
        del self.chat.messages[file_message_index]

    def chat_length(self):
        return len(self.chat.messages)

    def run(self, prompt, max_iter=25):
        remove_tools = self.get_tool_mask()
        res = super().run(prompt, remove_tools=remove_tools, max_iter=max_iter)
        return res

    def run_with_todo_list(self, prompt: str, max_iter: int = 10) -> str:
        """Main execution method that uses todo list for task management."""
        if self.verbose:
            print(f"[RASPA] RaspaAgent received instruction: {prompt}")

        # Add initial progress message
        self.print_progress("execution_start", f"RaspaAgent starting execution of: {prompt[:100]}...")

        try:
            # Step 1: Decompose the instruction into a todo list
            todo_list_markdown = self.decompose_task(prompt)

            if not todo_list_markdown:
                return "Could not decompose the instruction into actionable tasks. Please provide a more specific instruction."

            # Extract tasks for display
            tasks = self._extract_tasks_from_markdown(todo_list_markdown)

            if self.verbose:
                print(f"[DECOMPOSE] Decomposed into {len(tasks)} tasks:")
                print(todo_list_markdown)

            # Step 2: Execute the todo list using tools
            self.print_progress("execution_phase", "Starting execution of todo list")
            execution_results = self.execute_todo_list_with_tools(todo_list_markdown, max_iter)

            # Step 3: Prepare summary
            self.print_progress("summary_generation", "Generating execution summary")
            summary = self._generate_summary(prompt, execution_results)

            self.print_progress("execution_final_complete", "RaspaAgent execution complete.")

            return summary

        except Exception as e:
            error_msg = f"RaspaAgent encountered an error: {str(e)}"
            self.print_progress("execution_error", f"RaspaAgent execution failed: {str(e)}")
            if self.verbose:
                print(f"[ERROR] {error_msg}")
            return error_msg

    def _run(self, options, append_files=True):
        if append_files:
            index = self.add_file_message()
            out = super()._run(options)
            self.remove_file_message(index)
        else:
            out = super()._run(options)
        return out

    def _advance_to_next_folder(self):
        """
        Find the next available folder (simulation_N) in self.path, create it, and set as path_add.
        """
        base_path = self.path
        os.makedirs(base_path, exist_ok=True)
        prefix = "simulation_"
        existing_folders = [
            d for d in os.listdir(base_path)
            if os.path.isdir(os.path.join(base_path, d)) and d.startswith(prefix) and d[len(prefix):].isdigit()
        ]
        if existing_folders:
            nums = [int(d[len(prefix):]) for d in existing_folders]
            max_num = max(nums)
            # If the highest-numbered folder is empty, reuse it
            highest_folder = f"{prefix}{max_num}"
            if not os.listdir(os.path.join(base_path, highest_folder)):
                next_num = max_num
            else:
                next_num = max_num + 1
        else:
            next_num = 1
        new_folder = f"{prefix}{next_num}"
        new_path = os.path.join(base_path, new_folder)
        os.makedirs(new_path, exist_ok=True)
        self.set_path_add(new_folder)
        return new_path

    def get_tool_mask(self):
        mask = []

        if self.active_learning is False:
            mask.append("learn")

        # self.auto_run controls visibility of the raspa tool:
        if self.auto_run is False:
            mask.append("execute raspa")

        # all required files need to be present:
        # elif not self.check_files():
        #    return ["raspa"]

        return mask

    def setup(self):
        # self.init_special_memories()
        return

    def print_progress(self, message_type: str, details: str):
        """Print progress messages during execution."""
        print(f"[{message_type}]: {details}")

    def get_tool_list_prompt(self):
        """Generate tool descriptions dynamically."""
        tool_descriptions = []
        tool_names = []
        for tool_name, tool in self.tools.items():
            tool_descriptions.append(f"- {tool_name}: {tool.description}")
            tool_names.append(tool_name)

        tools_text = "\n".join(tool_descriptions)
        return tools_text

    def decompose_task(self, instruction: str) -> str:
        """Generate a markdown todo list directly from the instruction."""
        if self.verbose:
            print("[RASPA] Generating todo list directly from instruction...")

        # Add progress message
        self.print_progress("decomposition_start", f"Starting task decomposition for: {instruction[:100]}...")

        # Direct prompt to generate todo list
        todo_generation_prompt = f"""
        Analyze the following instruction and break it down into a actionable markdown todo list.
        You must ensure that the todo list you generate can be solved by the tools

        Instruction: {instruction}

        Available Tools:
        {self.get_tool_list_prompt()}

        Rules:
        - Use [ ] for incomplete tasks in markdown format
        - Each task should specify which tool to use from the available tools
        - The steps should be actionable with the available tools
        - Keep tasks focused and specific
        - The todo list can be as simple as one or two items

        Return only the markdown todo list, nothing else:
        - [ ] Task 1
        - [ ] Task 2
        """

        try:
            response = Chat(todo_generation_prompt).complete(cache=False, expensive=True)
            self.current_todo_list = response.strip()

            # Add progress message to display the generated todo list in chat
            self.print_progress("todo_list_generated", f"Generated todo list:\n\n{self.current_todo_list}")

            self.print_progress("decomposition_complete",
                                f"Task decomposed into todo list with {len(self._extract_tasks_from_markdown(self.current_todo_list))} tasks")
            return self.current_todo_list
        except Exception as e:
            error_msg = f"Could not generate todo list: {str(e)}"
            if self.verbose:
                print(f"[ERROR] {error_msg}")
            self.print_progress("decomposition_error", error_msg)
            return ""

    def update_todo_list_after_task(self, completed_task: str, task_result: str) -> str:
        """Update the todo list by marking completed task and potentially adding new tasks."""
        if not self.current_todo_list:
            return self.current_todo_list

        update_prompt = f"""
        Current todo list:
        {self.current_todo_list}

        A task was just completed:
        Task: {completed_task}
        Result: {task_result[:500]}...

        Please update the todo list by:
        1. Mark the completed task with [x] instead of [ ]
        2. If the result suggests new tasks are needed, add them as new [ ] items
        3. Return the complete updated todo list in markdown format

        Only return the updated todo list, nothing else.
        """

        try:
            response = Chat(update_prompt).complete(cache=False, expensive=True)
            updated_list = response.strip()
            self.current_todo_list = updated_list
            return updated_list
        except Exception as e:
            if self.verbose:
                print(f"[WARNING] Could not update todo list: {str(e)}")
            return self.current_todo_list

    def _suggest_next_action(self, todo_list_markdown: str, current_results: Dict[str, Any]) -> str:
        """Use LLM to suggest the next action based on the todo list and current progress."""

        # Build context from completed tasks
        completed_context = ""
        if current_results['completed_tasks']:
            completed_context = "\n\nCompleted tasks so far:\n"
            for task in current_results['completed_tasks']:
                completed_context += f"- {task['task']}\n  Result: {task['result'][:200]}...\n"

        next_action_prompt = f"""
        Current Todo List:
        {todo_list_markdown}

        Available Tools:
        {self.get_tool_list_prompt()}
        {completed_context}

        Based on the current todo list and progress, what should be the next action to take?

        Notice:
        - Return a action description that contains all the information to run the tool
        - Look at the todo list and identify the next incomplete task (marked with [ ])
        - Provide specific details needed to execute the task
        """

        try:
            response = Chat(next_action_prompt).complete(cache=False, expensive=True)
            next_action = response.strip()
            return next_action
        except Exception as e:
            if self.verbose:
                print(f"[WARNING] Could not suggest next action: {str(e)}")
            return "done"

    def _extract_tasks_from_markdown(self, markdown_todo: str) -> List[str]:
        """Extract task descriptions from markdown todo list."""
        tasks = []
        lines = markdown_todo.split('\n')

        for line in lines:
            line = line.strip()
            # Match markdown checkbox format: - [ ] or - [x]
            match = re.match(r'^-\s*\[\s*[x ]?\s*\]\s*(.+)$', line)
            if match:
                tasks.append(match.group(1).strip())

        return tasks

    def _all_tasks_completed(self, todo_list_markdown: str) -> bool:
        """Check if all tasks in the todo list are completed (marked with [x])."""
        if not todo_list_markdown.strip():
            return True  # Empty todo list means nothing to do

        lines = todo_list_markdown.split('\n')
        has_tasks = False

        for line in lines:
            line = line.strip()
            # Check for markdown checkbox format
            if re.match(r'^-\s*\[', line):
                has_tasks = True
                # If we find any incomplete task ([ ]), return False
                if re.match(r'^-\s*\[\s*\]\s*', line):
                    return False

        # If we found tasks and none were incomplete, all are completed
        # If we found no tasks at all, consider it completed
        return has_tasks

    def execute_todo_list_with_tools(self, todo_list_markdown: str, max_iter: int) -> Dict[str, Any]:
        """Execute the markdown todo list using tools through the Agent framework."""
        results = {
            'completed_tasks': [],
            'failed_tasks': [],
            'total_tasks': 0,
        }

        max_iterations = min(max_iter, 20)  # Prevent infinite loops
        iteration = 0

        # Build context from previous completions
        context_summary = ""

        while iteration < max_iterations:
            # Check if all tasks in the todo list are completed (marked with [x])
            if self._all_tasks_completed(self.current_todo_list):
                if self.verbose:
                    print("[RASPA] All tasks completed - todo list shows all [x]")
                self.print_progress("execution_complete", "All tasks completed - todo list shows all [x]")
                break

            iteration += 1

            # Use LLM to suggest next action based on current todo list
            next_action = self._suggest_next_action(self.current_todo_list, results)

            if self.verbose:
                print(f"\n[RASPA] Iteration {iteration}: {next_action}")

            self.print_progress("task_start", f"Starting task {iteration}: {next_action}")

            try:
                # Build action prompt with context from previous tasks
                if context_summary:
                    action_prompt = f"""Execute this specific task: {next_action}

Context from previous completed tasks:
{context_summary}

Please execute the task taking into account the previous work done."""
                else:
                    action_prompt = f"Execute this specific task: {next_action}"

                # Get tool mask for current state
                remove_tools = self.get_tool_mask()

                # Use parent StudentAgent's run method to execute this single action
                result = super(RaspaAgent, self).run(action_prompt, max_iter=5, remove_tools=remove_tools)

                # Print the actual result for visibility
                if self.verbose:
                    print(f"[RESULT] Task result: {result[:500]}...")

                self.print_progress("task_result", f"Result: {result[:300]}...")

                # Update context summary with this completion
                context_summary += f"\nTask: {next_action}\nResult: {result[:500]}\n"

                # Update todo list after task completion
                self.update_todo_list_after_task(next_action, result)

                self.print_progress("todo_list", f"{self.current_todo_list}")

                results['completed_tasks'].append({
                    'task': next_action,
                    'result': result,
                    'status': 'completed'
                })

                if self.verbose:
                    print(f"[SUCCESS] Task completed successfully")

            except Exception as e:
                error_result = {
                    'task': next_action,
                    'error': str(e),
                    'status': 'failed'
                }
                results['failed_tasks'].append(error_result)
                self.print_progress("task_error", f"Task failed: {next_action}. Error: {str(e)}")

                if self.verbose:
                    print(f"[FAILED] Task failed: {str(e)}")

        results['total_tasks'] = len(results['completed_tasks']) + len(results['failed_tasks'])
        return results

    def _generate_summary(self, original_instruction: str, execution_results: Dict[str, Any]) -> str:
        """Generate a comprehensive summary of the execution."""
        summary = f"""
## Execution Summary

**Original Instruction:** {original_instruction}

### Final Todo List Status:
{self.current_todo_list}

### Completed Tasks ({len(execution_results['completed_tasks'])}):
"""

        for i, task_result in enumerate(execution_results['completed_tasks'], 1):
            summary += f"\n**Task {i}:** {task_result['task']}\n"
            summary += f"**Result:** {task_result['result'][:1000] if task_result['result'] else 'No result captured'}\n"
            if len(task_result['result']) > 1000:
                summary += f"... (result truncated)\n"

        if execution_results['failed_tasks']:
            summary += f"\n### Failed Tasks ({len(execution_results['failed_tasks'])}):\n"
            for i, task_result in enumerate(execution_results['failed_tasks'], 1):
                summary += f"\n**Task {i}:** {task_result['task']}\n"
                summary += f"**Error:** {task_result['error']}\n"

        summary += f"\n### Total: {execution_results['total_tasks']} tasks processed\n"
        return summary

    def set_auto(self, auto):
        self.auto_run = auto
        return